forge "https://forgeapi.puppetlabs.com"

mod 'puppetlabs/apt'
mod 'tylerwalts/jdk_oracle'
mod 'maestrodev/maven'
mod 'puppetlabs/docker_platform'
mod 'nvpuppet/gitolite'
mod 'puppetlabs/postgresql'

mod 'alkivi/ldap',
  :git => "git://github.com/alkivi-sas/puppet-ldap.git"
