forge "https://forgeapi.puppetlabs.com"

mod 'puppetlabs/apt'
mod 'tylerwalts/jdk_oracle'
mod 'maestrodev/maven'
mod 'garethr/docker'
mod 'nvpuppet/gitolite'
mod 'puppetlabs/postgresql'
mod 'datacentred/ldap'
